import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Stick } from "next/font/google";

const stick = Stick({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={stick.className}>{children}</body>
    </html>
  );
}
